name: Regenerate PluginMaster
on: 
  workflow_dispatch:
  push:
    branches:
    - master
concurrency: regenerate
jobs:
  generate:
    name: Regenerate PluginMaster
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v3
        with:
            python-version: '3.8'
      - uses: actions/checkout@v3
        with:
          fetch-depth: '0'
      - name: Generate PluginMaster
        run: python generate_pluginmaster.py
      - uses: EndBug/add-and-commit@v9
        with:
          author_name: GitHub Action
          author_email: action@github.com
          message: Regenerate PluginMaster